apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp1
spec:
  replicas: 5
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: c1
        image: image